# Azure Pipelines config for ntRoot CI
# See https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true

  - script: |
      echo "Installing Miniforge..."
      curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -o miniforge.sh
      bash miniforge.sh -b -p $HOME/miniforge3
      rm miniforge.sh
      echo "##vso[task.prependpath]$HOME/miniforge3/bin"
    displayName: Install conda

  - script: |
      conda create --yes --quiet --name ntroot_CI python=3.12
      source $HOME/miniforge3/etc/profile.d/conda.sh
      conda activate ntroot_CI
      conda install --yes -c conda-forge -c bioconda mamba
      mamba install --yes -c conda-forge -c bioconda meson ninja snakemake perl 'ntedit>=2.0.1' samtools bedtools libcxx llvm btllib zlib boost cmake compilers
    displayName: Create and install Conda environment
  
  - script: |
      source $HOME/miniforge3/etc/profile.d/conda.sh
      conda activate ntroot_CI
      export PATH=$(pwd):$PATH
      which ntroot
      which ntedit
      cd demo
      ./run_ntroot_demo.sh
    displayName: Run ntRoot test

- job:
  displayName: macOS-latest
  pool:
    vmImage: 'macOS-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true

  - script: |
      echo "Installing Miniforge..."
      curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-x86_64.sh -o miniforge.sh
      bash miniforge.sh -b -p $HOME/miniforge3
      rm miniforge.sh
      echo "##vso[task.prependpath]$HOME/miniforge3/bin"
    displayName: Install conda

  - script: |
      conda create --yes --quiet --name ntroot_CI python=3.12
      source $HOME/miniforge3/etc/profile.d/conda.sh
      conda activate ntroot_CI
      conda install --yes -c conda-forge -c bioconda mamba
      mamba install --yes -c conda-forge -c bioconda snakemake perl 'ntedit>=2.0.1' samtools bedtools libcxx llvm meson ninja btllib zlib boost cmake compilers
    displayName: Create and install Conda environment
  
  - script: |
      source $HOME/miniforge3/etc/profile.d/conda.sh
      conda activate ntroot_CI
      export PATH=$(pwd):$PATH
      which ntroot
      cd demo
      ./run_ntroot_demo.sh
    displayName: Run ntRoot test
