# See https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true

  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name ntroot_CI
    displayName: Create Anaconda environment
  - script: |
      source activate ntroot_CI
      conda install --yes --name ntroot_CI -c conda-forge -c bioconda python=3.9 mamba
      mamba install --yes -c conda-forge -c bioconda meson ninja snakemake perl 'ntedit>=2.0.1' samtools
    displayName: Install Conda packages
  
  - script: |
      source activate ntroot_CI
      export PATH=$(pwd):$PATH
      which ntroot
      cd demo
      ./run_ntroot_demo.sh
    displayName: Run ntRoot test

- job:
  displayName: macOS-latest
  pool:
    vmImage: 'macOS-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true

  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name ntroot_CI
    displayName: Create Anaconda environment
  - script: |
      source activate ntroot_CI
      conda install --yes --name ntroot_CI -c conda-forge -c bioconda python=3.9 mamba
      mamba install --yes -c conda-forge -c bioconda snakemake perl 'ntedit>=2.0.1' samtools
    displayName: Install Conda packages
  
  - script: |
      source activate ntroot_CI
      export PATH=$(pwd):$PATH
      which ntroot
      cd demo
      ./run_ntroot_demo.sh
    displayName: Run ntRoot test
